### ISSUE TITLE
Having a hard time understanding the motivation behind having no control over the log-level

### ISSUE THREAD

**Issue by Madd0g** [gajus/roarr#12]
I like a lot of things about this logger, but I'm struggling to understand why there's no control for the log-level anywhere, why isn't that another environment variable?

if I want to use `TRACE` a lot when developing but don't want production to trace anything unless somehow told to, is there no way of controlling that besides using an external json filterer?

jq is another dependency to bring in - is the official suggestion to use jq in production? or find a "transport" that can do the filtering?

Thanks

**Comment by gajus** [comment]
> I like a lot of things about this logger, but I'm struggling to understand why there's no control for the log-level anywhere, why isn't that another environment variable?

The simple answer is – separation of concerns.

Your application is doing its job and producing logs. What logs are being produced is not a concern of the application.

I am personally logging _everything_, sending it off to elastic search and then have a curator filter that deletes all logs `logLevel` < 20 that are older than a day. Neither performance or memory is an issue, because log processing is happening out of the main process and you are able to adjust log life span however you want.

However, you could equally bring `jq` as a dependency, as you've suggested. I wouldn't do that, simply because inspecting issues across all the applications in the cluster would require adjusting what logs those applications are sending. Which goes back to the original point – separation of concerns – your cluster programs are doing their job and producing logs; you shouldn't need to adjust cluster configuration/ program execution pipeline to get other/ different logs.

In your case, where do the logs go, how do you analyse them and whats the issue with sending all the logs?

**Comment by Madd0g** [comment]
I want to be able to look deep into the application while developing, keeping only the TRACE level really noisy and verbose and the other levels really clean and thought out.

I simply don't want to store or transport all those TRACE messages because they tend to be much bigger and they are never crucial, all critical things are covered by higher levels. I know disk space is cheap these days, but I just want to draw a line and say, anything under this level is not sent anywhere by default.

Right now I'm using all textual logs, which I can filter by the log level by keyword like `[DEBUG]` and I just shove structured (json) logs in there and conditionally parse them down the line. 

I want to switch to fully structured logging everywhere. I don't use anything like TRACE currently and I want to introduce this level of logging, for things that almost never break but it's important to be able to see their output somehow. But even when developing, I would usually want to disable this mode because it would be really noisy.

**Comment by gajus** [comment]
> I simply don't want to store or transport all those TRACE messages because they tend to be much bigger and they are never crucial, all critical things are covered by higher levels.

What are you proposing as a solution?

I will not add a change that adds ability to strip logs from within the application, even if thats using environment variables.

However, I can somewhat see value having `roarr filter` function, i.e. `your-app | roarr filter --min-log-level 40` or something along those lines.

> But even when developing, I would usually want to disable this mode because it would be really noisy.

I am developing roarr web UI for that. :-)

**Comment by Madd0g** [comment]
> However, I can somewhat see value having `roarr filter` function, i.e. `your-app | roarr filter --min-log-level 40` or something along those lines

That means another component that will re-parse and filter all those JSON messages, maybe it's silly to worry about this tiny out-of-process cost, but I can't help it.

Ok, thanks, I'll keep thinking about my idea of adding lots of new logging via TRACE. Maybe I'll hide it behind some application config.

**Comment by gajus** [comment]
> That means another component that will re-parse and filter all those JSON messages, maybe it's silly to worry about this tiny out-of-process cost, but I can't help it.

Unless you are producing tens of thousands of logs a minute, it is a silly thing to worry about. I consider my applications extremely log intensive and ... logging is nowhere near at the top of my performance concerns.
