### ISSUE TITLE
Changing `ROARR_LOG` at runtime has no effect

### ISSUE THREAD

**Issue by Aankhen** [gajus/roarr#28]
Example `index.mjs` (please ignore the gymnastics to run it under Node 13.5.0):

```js
process.env.ROARR_LOG = undefined;

import log from "roarr";

log.default("This should be hidden");

process.env.ROARR_LOG = "true";

log.default("This should be shown");
```

Running it (Windows):

```
λ set ROARR_LOG=true

λ node index.mjs
(node:6088) ExperimentalWarning: The ESM module loader is experimental.
{"context":{},"message":"This should be hidden","sequence":0,"time":1577971598534,"version":"1.0.0"}
{"context":{},"message":"This should be shown","sequence":1,"time":1577971598535,"version":"1.0.0"}

λ set ROARR_LOG=

λ node index.mjs
(node:7116) ExperimentalWarning: The ESM module loader is experimental.
```

This behaviour is because the decision to log or not to log is made the first time the module is loaded:

https://github.com/gajus/roarr/blob/5f856d969d5455727bbea770e1f5402ae04cd66c/src/log.js#L20-L27

Defining `ROARR_LOG` in a `.env` file then fails, because `roarr` will be loaded before that file is ever read and parsed. I think this is the correct behaviour in and of itself; I would just suggest exporting `createLogger` and `createMockLogger` so that something like this works:

```js
import { processDotEnvFile } from "my-dotenv-module";
import { createLogger, createMockLogger } from "roarr";

/* … */

const someFile = getFileNameFromUser();
processDotEnvFile(someFile);
const LOGGER = (process.env.SHOULD_LOG) ? createLogger() : createMockLogger();
```

**Comment by pskopnik** [comment]
I would also like to see a way to create a definitely-logging logger in my own code.
For applications there may be rules about logging which are solved in-code and should not be handed-off to the user/operator, who has to set `ROARR_LOG` accordingly. E.g. a batch process should definitely log except if the `--quiet` flag is passed on the CLI.

Would you consider a PR exposing two variants of the `logFactory(...)` in `log.ts`, one for `createLogger` and one for `createMockLogger`?

**Comment by gajus** [comment]
I am not able to understand the use case.

Can you give an example of when it would be desirable to start the application without logging, but then enable logging later, or vice versa?

**Comment by Aankhen** [comment]
It’s not so much about starting the application without logging and then enabling logging later, though I understand that the title makes it sound like that. Rather, it’s about controlling the logging in the application, as @pskopnik mentioned. For example, as I said in the report, using a `.env` file to control logging fails because that file is read at runtime, before `roarr` decides whether to log or not. Transpilation makes this even more complicated because, depending on the process, that variable might be read at any point during the transpilation rather than when the program is run.

If `createLogger` and `createMockLogger` were exposed, it would be possible for the application itself to control whether logging was enabled and to customize it.

**Comment by gajus** [comment]
>  it’s about controlling the logging in the application,

For what use case?

It is not program's responsibility to say when it should log.

It is the responsibility of the executing process.

I am closing this, but happy to continue the discussion.

**Comment by pskopnik** [comment]
Every program has a "contract" of how to use/interact with it, essentially its interface and the underlying guarantees.
How the program behaves on an invocation is thus negotiated between the program and the user. Each (serious) program has one/multiple ways of accepting and processing this kind of information: Defaults, config files, CLI flags, environment variables, ....
As a developer I would like to integrate logging into these and have my program behave accordingly. After all, logging is part of the interface of my program.
Otherwise, users have to negotiate basics of logging with the logging library, past my program. That is pretty unusual.
From a maintainability perspective there is a further disadvantage to the "user -> logging library" approach: I cannot simply refactor my program and switch the library after that, because that would change the interface. Generally I would like to hide the the details of implementation, e.g. which libraries I've chosen, from my users.

Use cases are all programs where logging is part of the primary user interface/program interface.

 * A batch process which runs for a few hours and performs complex actions (backup process, data-intensive workflow, encoding video, ...). Logging is likely the only output during runtime, probably enabled by default so that output is analysed for errors & warnings or simply archived.
 * A server/daemon where logging is the primary output, documenting the processed requests. Logging is probably enabled by default on stdout and output is collected by the process supervisor (systemd, docker, ...).

I think the `ROARR_LOG` approach works well when developing packages to be integrated into others' programs, as there is no straightforward way to interact with the user. Logging may be used primarily for debugging in this case.
But when developing applications, logging might be a primary form of output and in this case I think it should be part of the regular user interface/program interface.

Thus, it would be convenient if roarr exposed primitives to enable/disable logging as well as deciding where to write (stdout or stderr) to my application's code.

**Comment by gajus** [comment]
If you are able to hardcode `ROARR_LOG=true`, then you can just override `ROARR.write` (like in the [browser example](https://github.com/gajus/roarr#browser)) and enable / disable however you like (because you control `ROARR.write` implementation`.

Does that not solve your problem?

**Comment by pskopnik** [comment]
We had to drop the project which had the particular use case described above and I can no longer advocate for any solutions.

I came up with two workarounds for the problem back then:

1. Overwriting the env var `ROARR_LOG=true` within the node process.
   This "initialiser" must be run before roarr is imported for the first time. This may be difficult because import-order is rarely a concern and particularly with TypeScript it isn't obvious when a module is imported for only for its types (no runtime effect) or also for using its exported variables.

2. Creating a separate roarr logger instance and passing this around to all application components which may use logging.
   This goes against the motivation of roarr as a globally available logger and breaks for any external libraries which import roarr (which still relies on `ROARR_LOG`). It also requires replicating [parts of this code in the project](https://github.com/gajus/roarr/blob/master/src/Roarr.ts#L27-L68) and importing `createLogger` from `roarr/dist/src/factories`.
