### ISSUE TITLE
Why is it bad to instantiate a logger?

### ISSUE THREAD

**Issue by gaastonsr** [gajus/roarr#4]
> Unfortunately, you still need to instantiate logger instance at the application-level. This makes it more suitable for application-level logging just like Winston and Bunyan.

I'm looking for a logger for one of my apps and I stumbled upon Roarr. Looks pretty good. The only question I have is, why is it bad to instantiate a logger at the application level?

And when you say instantiate you mean "new Logger()"? if you could expand more on this point I would appreciate it.

Thanks.

**Comment by gajus** [comment]
> And when you say instantiate you mean "new Logger()"? if you could expand more on this point I would appreciate it.

Yes.

It is bad for packages.

It isn't necessarily bad for applications.

But ideally you want to use the same logger applications and packages.

The reason it is bad for packages, is because most packages export pure utility functions which do not give an opportunity to provide configuration of a logger (e.g. lodash).

**Comment by gaastonsr** [comment]
Ok, I think I get your point. Thanks!
