### ISSUE TITLE
Allow filtering by logger name

### ISSUE THREAD

**Issue by Hades32** [gajus/roarr#56]
https://github.com/visionmedia/debug let's you enable logs on a per logger basis (via `DEBUG=mymodule:*`) whereas Roar only allows on/off (via `ROARR_LOG=1/0`).

I want to be able to filter by logger name, too, so even when every module starts using Roar I can still read my logs

**Comment by gajus** [comment]
Already exists

https://github.com/gajus/roarr-cli

**Comment by Hades32** [comment]
This is not what I mean @gajus. I don't want those logs to be printed in the first place. The CLI is just a convenience tool to filter log streams/files afterward, but they are still written to the console.

If I have a service with very high load, I don't want to enable logging for ALL my dependencies, as that would be cost-prohibitive when I'm storing the logs...

**Comment by gajus** [comment]
Please read https://github.com/gajus/roarr#roarr-motivation

It's very much an intentional design choice.

A section about anti-patterns describes a way how you could do it if you really wanted.

https://github.com/gajus/roarr#anti-patterns

That being said, Roarr is being used without these workarounds in environments handling thousands of requests / second with no issue.

**Comment by Hades32** [comment]
I actually did read the motivation, and my feature request matches it quite well and I can't see a contradiction. It's still via env-vars, just like `debug` which you cite, and doesn't invalidate any of your other design goals (as stated in the readme at least).

So, if this is by design, I respect that of course, but maybe you want to make this clearer in the non-goals, as to me it's still not clear why.

**Comment by gajus** [comment]
The problem with this suggestion is that it would add additional performance load to the same process that the application itself is running. The reason for using a separate tool like `roarr-cli` is because it does filtering out of process. This makes it easier to scale filtering and other log related logic.

**Comment by gajus** [comment]
It's the first bullet-point in motivation ("Does not block the event cycle (=fast).")

Happy to amend the documentation if it is not clear what it refers to.

**Comment by Hades32** [comment]
Ah, I see what you mean. But maybe we're thinking about a possible implementation differently, because I don't think this would impose any performance penalty: 
I imagined that this check would happen as part of the logger creation (something that I expect to only happen once during app startup) and therefore individual `log.info(...)` calls wouldn't be affected (at least not more than they are by `ROARR_LOG=false`).

The benefit of some(*) filtering on the library level would be to avoid costly serializations or potentially whole method calls needed to collect trace information.

*) I definitely agree, that most filtering should happen in Loki, ElasticSearch and whatever log-aggregator you're using.

**Comment by gajus** [comment]
I don't see how what you described could be achieved. If there was a way to do this without performance penalty, I would not be against it.
